### ISSUE TITLE
The Controller in the Config file

### ISSUE THREAD

**Issue by vint2000** [Ejimba/pesapal#2]
I am working on an application where I want to update other tables if the status is valid.
How do I get to use the Controller?
If you could show me an example I would greatly appreciate it.
:+1:

**Comment by Ejimba** [comment]
Let say you have a controller PesapalController to handle updating of the tables you are referring to.
Create a method with a name "updateItem" taking 2 params "key" and "reference"

```php
<?php

class PesapalController extends BaseController {

	// other methods for handling pesapal payments

	public function updateItem($key,$reference)
	{
		// the if statement is to prevent some hacker from trying to buy
		// a product without paying
		// ensure to change the key in pesapal config

		// you can also add a check so that only certain
		// ips (PESAPAL SERVER IPS) run this method

		// this method should NOT be in your routes file!!
		// it will execute whether its in route.php or not

		if($key == Config::get('pesapal::key'))
		{
			// update your tables in here
			// the reference here is the same reference
			// (unique key to the transaction) you created
			// when you were charging the customer
			
			$product_sale = ProductSale::where('pesapal_ref', '=', $reference)->first();
			
			if(!is_null($product_sale))
			{
				$product_sale->confirmed = 1;
				$product_sale->save();

			}
		}

	}

	// other methods for handling pesapal payments

```

**Comment by vint2000** [comment]
Hello again,
My tables are not yet updating:
I set my controller in the config file to: 'controller' => "PesapalController",
and the Controller as follows:

<?php

class PesapalController extends BaseController {

    // other methods for handling pesapal payments

    public function updateItem($key,$reference)
    {
        // the if statement is to prevent some hacker from trying to buy
        // a product without paying
        // ensure to change the key in pesapal config

        // you can also add a check so that only certain
        // ips (PESAPAL SERVER IPS) run this method

        // this method should NOT be in your routes file!!
        // it will execute whether its in route.php or not

        if($key == Config::get('pesapal::key'))
        {
            // update your tables in here
            // the reference here is the same reference
            // (unique key to the transaction) you created
            // when you were charging the customer

            $invoice = Invoice::where('pesapal_ref', '=', $reference)->first();
          
            if(!is_null($invoice))
            {
            $invoice->paid = '1';
            $invoice->expiry_of_subscription = '2015-10-14 08:03:09';
            $invoice->save();
            }
            
        }

    }

    // other methods for handling pesapal payments

Invoice Model:
<?php
class Invoice extends BaseModel  {
	
	protected $table = 'invoice';
	protected $primaryKey = 'id';

	public function __construct() {
		parent::__construct();
		
	}

	public static function querySelect(  ){
		
		
		return "  SELECT invoice.* FROM invoice  ";
	}
	public static function queryWhere(  ){
		
		return " WHERE invoice.id IS NOT NULL   ";
	}
	
	public static function queryGroup(){
		return "  ";
	}
	

}

Please assist me Ejimba. Thanks in Advance

**Comment by vint2000** [comment]
Hey,
Still can't update my tables.

**Comment by Ejimba** [comment]
Please check your log file (app/storage/logs/laravel.log) and scroll towards the end of the file and see if Pesapal has thrown any errors and if any, post the error here.

FYI: Make sure you have updated your IPN in Pesapal Control Panel to point to the Application Server IP. 
FYI2: IPN doesn't work while on localhost

**Comment by vint2000** [comment]
Thanks for your feedback.
I am not running my application on localhost. The pesapalpayments table fields: status and tracking_id are being updated, though the controller doesn't update my other app tables.
Laravel.log 
//
[2015-10-15 09:07:54] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/protected/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:146
Stack trace:
#0 /var/www/html/protected/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/protected/vendor/laravel/framework/src/Illuminate/Routing/Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/protected/vendor/laravel/framework/src/Illuminate/Routing/Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/protected/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/protected/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/protected/vendor/laravel/framework/src/Illuminate/Http/FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/protected/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/protected/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/protected/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/protected/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 /var/www/html/protected/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 /var/www/html/index.php(50): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2015-10-15 09:08:35] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected end of file, expecting function (T_FUNCTION)' in /var/www/html/protected/app/controllers/PesapalController.php:39
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-10-15 09:08:36] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected end of file, expecting function (T_FUNCTION)' in /var/www/html/protected/app/controllers/PesapalController.php:39
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-10-15 09:08:36] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected end of file, expecting function (T_FUNCTION)' in /var/www/html/protected/app/controllers/PesapalController.php:39
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-10-15 09:08:36] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected end of file, expecting function (T_FUNCTION)' in /var/www/html/protected/app/controllers/PesapalController.php:39
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
//

**Comment by Ejimba** [comment]
You seem to have a syntax error on PesapalController.php line 39. Maybe a missing semicolon perharps? Please check PesapalController.php line 39.

**Comment by vint2000** [comment]
Silly me! Thanks Ejimba.

**Comment by Ejimba** [comment]
You are welcome
